### ISSUE TITLE
Freezes / Lag

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [kwmcrell/ArmedCards#66]
Hello there,

Sometimes when the Czar has to pick a card, he click it, click "done" and nothing happens... we have to wait for some seconds until it actually "picks" the card... So I guess it's a server lag or something, it's really annoying sometimes.

Could you confirm that it is caused by a server "lag" or something else ? 

Best Regards.
Ps : We all love ArmedCards, tons of fun at night with friends ;)

**Comment by kwmcrell** [comment]
Yes it does seem to be server lag.  I'm sorry for the incovience.  We are in the process of getting some sort of "loading" indicator up so that the user knows that server is processing.

Thank you for the kind words.  I'm glad you guys are enjoying it.

**Comment by Sakarias-Longhorn** [comment]
Oh, Do you think you could add some kind of "avatar" setting ? for exemple.. I think the easiest way to do that would be to use the GRAVATAR api.

**Comment by RetroEvolute** [comment]
That was actually our plan originally, and then I found some cute pictures of cats and we got distracted.

Maybe kwmcrell will implement that now. Thanks for the feedback. We really appreciate it. :)

**Comment by Sakarias-Longhorn** [comment]
This is really the best "remake" of CAH I could find online, It's so pleasant to play, and it "look" really good actually.. the only show stoppers right now are the random "lags", we have to reload the page to fix it sometimes (And sometimes the server timeouts apparently), but anyway, you guys are doing an amazing job with that fork, Keep it up!

**Comment by RetroEvolute** [comment]
Thanks! We'll look into the performance stuff a bit more, but I'm pretty certain it's database server related, to which we have a few options to better our performance. As far as the design goes, we started this project with the same impression that the online CAH alternatives just weren't quite up to snuff. Glad you appreciate the effort!

Keep playing and spread the word!

**Comment by kwmcrell** [comment]
Just so you know I have implemented Gravatar now.  To get it to work you will just need to sign out and sign back in.
